version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: base
    container_name: server
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8041:80 # for nginx reverse proxy
    networks:
      - back-tier
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - back-tier

volumes:
  mysql_data:
networks:
  back-tier: